# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: JFrogMaven@1
  inputs:
    mavenPomFile: 'maven-examples/maven-example/pom.xml'
    goals: 'install'
    artifactoryResolverService: 'JFrog'
    targetResolveReleaseRepo: 'aemo-libs-release'
    targetResolveSnapshotRepo: 'aemo-libs-snapshot'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    projectKey: 'vigneshs-dev'
    javaHomeOption: 'JDKVersion'

- task: JFrogPublishBuildInfo@1
  inputs:
    artifactoryConnection: 'JFrog'
    projectKey: 'vigneshs-dev'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'

- task: JFrogBuildPromotion@1
  inputs:
    artifactoryConnection: 'JFrog'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    projectKey: 'vigneshs-dev'
    targetRepo: 'vigneshs-libs-snapshot-local'
    status: 'Released'
    sourceRepo: 'aemo-libs-snapshot-local'
    includeDependencies: false
    copy: true
    dryRun: false