# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: ArtifactoryMaven@2
  inputs:
    mavenPomFile: 'maven-examples/maven-example/pom.xml'
    goals: 'install'
    artifactoryResolverService: 'Artifactory'
    targetResolveReleaseRepo: 'aemo-libs-release'
    targetResolveSnapshotRepo: 'aemo-libs-snapshot'
    artifactoryDeployService: 'Artifactory'
    targetDeployReleaseRepo: 'aemo-libs-release'
    targetDeploySnapshotRepo: 'aemo-libs-snapshot'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'

- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: 'Artifactory'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'